CREATE PROC dbBackup
AS 
BEGIN
	BACKUP DATABASE [s17guest57] TO  DISK = N'D:\CSUN\Comp 440\SQL Saturday' WITH NOFORMAT, NOINIT,  NAME = N's17guest38-Full Database Backup', SKIP, NOREWIND, NOUNLOAD,  STATS = 10
END
GO
